Added check to make sure the sorting column exists
Attempting to not have a default sort causes an issue where it assumes there will always be a sort column. 
From FireBug: 
TypeError: aoColumns[srcCol] is undefined
aDataSort = aoColumns[ srcCol ].aDataSort;